const colors = {
  light: {
    text: "#0A0A1A",
    tint: "#8B5CF6",
    background: "#F8F7FF",
    foreground: "#0A0A1A",
    card: "#FFFFFF",
    cardForeground: "#0A0A1A",
    primary: "#8B5CF6",
    primaryForeground: "#FFFFFF",
    secondary: "#EC4899",
    secondaryForeground: "#FFFFFF",
    muted: "#EDE9FE",
    mutedForeground: "#6B5B95",
    accent: "#A855F7",
    accentForeground: "#FFFFFF",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    border: "#DDD6FE",
    input: "#DDD6FE",
    live: "#FF3B5C",
    online: "#10B981",
    gold: "#F59E0B",
    surface: "#F0EEFF",
    surfaceHigh: "#E8E0FF",
  },
  dark: {
    text: "#FFFFFF",
    tint: "#8B5CF6",
    background: "#0B0B18",
    foreground: "#FFFFFF",
    card: "#141428",
    cardForeground: "#FFFFFF",
    primary: "#8B5CF6",
    primaryForeground: "#FFFFFF",
    secondary: "#EC4899",
    secondaryForeground: "#FFFFFF",
    muted: "#1E1E3A",
    mutedForeground: "#9898B8",
    accent: "#A855F7",
    accentForeground: "#FFFFFF",
    destructive: "#FF3B5C",
    destructiveForeground: "#FFFFFF",
    border: "#1E1E3A",
    input: "#1E1E3A",
    live: "#FF3B5C",
    online: "#10B981",
    gold: "#F59E0B",
    surface: "#0F0F20",
    surfaceHigh: "#1A1A30",
  },
  radius: 12,
};

export default colors;
